
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMENTARIO ID NUM_DEC NUM_INT OPERADOR PALAVRA_RESERVADA SIMBOLO_ESPECIAL TEXTODeclaracaoVariavel : Tipo ID Finalizacao\n                          | Tipo ID Opatribuicao Expressao FinalizacaoTipo : PALAVRA_RESERVADA\n        Expressao : ID\n                 | NUM_INT\n                 | NUM_DECFinalizacao : SIMBOLO_ESPECIALOpatribuicao : OPERADOR'
    
_lr_action_items = {'PALAVRA_RESERVADA':([0,],[3,]),'$end':([1,5,7,13,],[0,-1,-7,-2,]),'ID':([2,3,6,8,],[4,-3,9,-8,]),'SIMBOLO_ESPECIAL':([4,9,10,11,12,],[7,-4,7,-5,-6,]),'OPERADOR':([4,],[8,]),'NUM_INT':([6,8,],[11,-8,]),'NUM_DEC':([6,8,],[12,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'DeclaracaoVariavel':([0,],[1,]),'Tipo':([0,],[2,]),'Finalizacao':([4,10,],[5,13,]),'Opatribuicao':([4,],[6,]),'Expressao':([6,],[10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> DeclaracaoVariavel","S'",1,None,None,None),
  ('DeclaracaoVariavel -> Tipo ID Finalizacao','DeclaracaoVariavel',3,'p_DeclaracaoVariavel','Teste.py',75),
  ('DeclaracaoVariavel -> Tipo ID Opatribuicao Expressao Finalizacao','DeclaracaoVariavel',5,'p_DeclaracaoVariavel','Teste.py',76),
  ('Tipo -> PALAVRA_RESERVADA','Tipo',1,'p_Tipo','Teste.py',79),
  ('Expressao -> ID','Expressao',1,'p_Expressao','Teste.py',89),
  ('Expressao -> NUM_INT','Expressao',1,'p_Expressao','Teste.py',90),
  ('Expressao -> NUM_DEC','Expressao',1,'p_Expressao','Teste.py',91),
  ('Finalizacao -> SIMBOLO_ESPECIAL','Finalizacao',1,'p_Finalizacao','Teste.py',94),
  ('Opatribuicao -> OPERADOR','Opatribuicao',1,'p_Opatribuicao','Teste.py',99),
]
